# Generated by Django 5.0.4 on 2024-05-20 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammessage',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
