# Generated by Django 4.2.7 on 2024-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
