# Generated by Django 4.2.7 on 2024-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='adding_link_code_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
