# Generated by Django 4.2.7 on 2023-11-23 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamsApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
