# Generated by Django 4.2.7 on 2023-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0002_team_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
