# Generated by Django 4.2.7 on 2023-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
