# Generated by Django 4.2.7 on 2023-12-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0006_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
