# Generated by Django 4.2.7 on 2024-01-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0007_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='unique_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
