# Generated by Django 4.2.7 on 2024-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApi', '0008_alter_team_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='error',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
